import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import Menu from '../components/navbar/navbar.jsx'
import { useContext } from 'react'
import { Tema, TemaContexto } from '../components/context/context'

export default function Home() {
  const {theme} = useContext(Tema)
  const { toggleTheme } = useContext( Tema )
  return (
    <div id={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu/>
      <button id="button_teste" onClick={()=>toggleTheme()}>trocar</button>
      {theme}
      {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
    </div>
  )
}
